services:
  db:
    image: mysql:8.0
    container_name: mysql_db_jjk
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: jujutsu_kaisen_game
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: